os:
  - osx
  - linux
env:
  - CCATS2=GCC
  - CCATS2=CLANG
sudo: false
addons:
  apt:
    packages:
    - libgc-dev
    - libgmp-dev
    - libgtk-3-dev
    - libev-dev
    - libjson0-dev
    - libjansson-dev
before_install:
  - date
  - cd ${HOME}
  # Setting-up
  - export ATSHOME=${HOME}/ats-lang-anairiats-0.2.12
  - export ATSHOMERELOC=ATS-0.2.12
  # Install pkgs
  - ${TRAVIS_BUILD_DIR}/travis-ci/installpkg.sh
  # Download ATS1
  - ${TRAVIS_BUILD_DIR}/travis-ci/ats1_setup.sh 0.2.12
  # Download ATS2
  - export PATSHOME=${HOME}/ATS-Postiats
  - git clone https://github.com/githwxi/ATS-Postiats.git ATS-Postiats
  # Download ATS2-contrib
  - export PATSCONTRIB=${HOME}/ATS-Postiats-contrib
  - git clone https://github.com/githwxi/ATS-Postiats-contrib.git ATS-Postiats-contrib
  - export GCC=gcc
  - export CLANG=clang
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export GCC=gcc-4.9; fi
script:
  - ${GCC} --version
  - ${CLANG} --version
  # Building ATS1
  - cd ${ATSHOME}
  # ./configure&&make CC=${GCC} all
  - ./configure&&make CC=${GCC} all_ngc
  # Building ATS2
  - cd ${PATSHOME}
  - eval CC=\${${CCATS2}}
  - GCFLAG=-D_ATS_NGC
  # GCFLAG=-D_ATS_GCATS
  # GCFLAG=-D_ATS_GCBDW
  - C3NSTRINTKND=intknd
  # C3NSTRINTKND=gmpknd
  - make C3NSTRINTKND=${C3NSTRINTKND} -f Makefile_devl CC=${CC} GCFLAG=${GCFLAG} all
  - export PATH=${PATH}:${PATSHOME}/bin
  # Trying-out release process
  - cd ${TRAVIS_BUILD_DIR}
  - make -C ${PATSHOME}/src CBOOT
  - make -C ${PATSHOME}/src/CBOOT/prelude
  - make -C ${PATSHOME}/src/CBOOT/libc
  - make -C ${PATSHOME}/src/CBOOT/libats
  - make -C ${PATSHOME}/doc/DISTRIB atspackaging
  - make -C ${PATSHOME}/doc/DISTRIB atspacktarzvcf
  - make -C ${PATSHOME}/doc/DISTRIB cleanall
  # Building parsemit
  - (cd ${PATSHOME}/contrib/CATS-parsemit && make all)
  # Building atscc2js
  - (cd ${PATSHOME}/contrib/CATS-atscc2js && make all && mv -f atscc2js ${PATSHOME}/bin/.)
  # Building atscc2php
  - (cd ${PATSHOME}/contrib/CATS-atscc2php && make all && mv -f atscc2php ${PATSHOME}/bin/.)
  # Running regress test
  - cd ${TRAVIS_BUILD_DIR}
  - export Makefile_test=Makefile_test
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export Makefile_test=Makefile_test_osx; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export Makefile_test=Makefile_test_linux; fi
  - make -f ${Makefile_test} all
after_script:
  - date
  # HX-2017-01-17
